# Application Name
spring.application.name=Inventory Management

# Server Configuration
server.port=8080

# Logging Configuration
logging.level.com.example.audituser=INFO
logging.level.com.enterprise.audit.logging=INFO

# Jackson Configuration
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.time-zone=UTC 